
//
// @author hxAri (hxari)
// @create 2026-06-15 03:00
// @github https://github.com/uranite-lang/uranite
//
// Uranite Copyright (c) 2025 - hxAri <hxari@proton.me>
// Uranite Licence under GNU General Public Licence v3
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// any later version.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

#ifndef _URANITE_FMT_COMMENTS_COMMENT_REATTACHER_HPP_
#define _URANITE_FMT_COMMENTS_COMMENT_REATTACHER_HPP_

#include <string>
#include <vector>

#include "uranite-fmt/comments/comment-extractor.hpp"

namespace uranite::formatter::comments {
	
	/**
	 * @class CommentReattacher
	 * @brief Re-injection engine responsible for placing extracted comments back into formatted source text.
	 *
	 * Since the structural code formatter flattens and pretty-prints the AST into a new string,
	 * this class acts as the final post-processing pass. It maps the original layout positions
	 * of comments to their new logical coordinates, ensuring no developer descriptions or 
	 * doccomments are lost during formatting.
	 */
	class CommentReattacher {
			
		public:
			
			/**
			 * @brief Constructs a CommentReattacher initialized with a collection of extracted comments.
			 * @param extractedComments An ordered vector containing the cached comments and their layout parameters.
			 */
			CommentReattacher( const std::vector<CommentEntry>& extractedComments );
			
			/**
			 * @brief Re-attaches all cached comments into the newly formatted source code stream.
			 * * This method analyzes structural changes by comparing the raw original source layout 
			 * with the pretty-printed token flows, calculating the optimal alignment offsets to inject 
			 * leading, trailing, or floating comment blocks seamlessly.
			 * * @param formattedSource The clean, pretty-printed source text generated by the code formatter.
			 * @param originalSource The raw, unmutated source text read from disk prior to formatting.
			 * @return std::string The final finalized source code string containing both pretty-printed code and integrated comments.
			 */
			std::string reattach(
				const std::string& formattedSource,
				const std::string& originalSource
			);
			
		private:
			
			/** @brief Internal store holding the tokenized comment data entries waiting for placement routing. */
			std::vector<CommentEntry> extractedComments_;
		
	};

} // namespace uranite::formatter::comments

#endif // _URANITE_FMT_COMMENTS_COMMENT_REATTACHER_HPP_
