
//
// @author hxAri (hxari)
// @create 2026-06-15 12:00
// @github https://github.com/uranite-lang/uranite
//
// Uranite Copyright (c) 2025 - hxAri <hxari@proton.me>
// Uranite Licence under GNU General Public Licence v3
//

#include <filesystem>
#include <fstream>
#include <regex>
#include <sstream>
#include <stdexcept>

#include "lockfile.hpp"
#include "manifest.hpp"

namespace uranite::pkg {

	std::string LockfileManager::escapeYamlString( const std::string& input ) {
		std::string escaped;
		escaped.reserve( input.size() );
		for( size_t charIndex = 0; charIndex < input.size(); charIndex++ ) {
			char character = input[charIndex];
			if( character == '"' ) {
				escaped+= "\\\"";
			}
			else if( character == '\\' ) {
				escaped+= "\\\\";
			}
			else {
				escaped+= character;
			}
		}
		return escaped;
	}

	bool LockfileManager::exists( const std::string& filePath ) {
		return std::filesystem::exists( filePath );
	}

	Lockfile LockfileManager::readFromFile( const std::string& filePath ) {
		std::ifstream fileStream( filePath );
		if( fileStream.is_open() == false ) {
			throw std::runtime_error( "could not open lockfile: " + filePath );
		}

		std::ostringstream contentStream;
		contentStream << fileStream.rdbuf();
		std::string content = contentStream.str();

		Lockfile lockfile;

		std::unordered_map<std::string, std::unordered_map<std::string, ManifestParser::ConfigValue>> sections =
			ManifestParser::parseYaml( content );

		std::unordered_map<std::string, ManifestParser::ConfigValue>& metadataSection = sections["lock"];
		if( metadataSection.count( "version" ) > 0 ) {
			lockfile.lockfileFormatVersion = metadataSection["version"].stringValue;
		}

		static const std::regex validPackageNamePattern( "^[A-Za-z0-9_][A-Za-z0-9._-]{0,63}$" );

		for( std::pair<const std::string, std::unordered_map<std::string, ManifestParser::ConfigValue>>& sectionPair : sections ) {
			std::string sectionName = sectionPair.first;
			if( sectionName.rfind( "package.", 0 ) != 0 ) {
				continue;
			}

			std::string packageName = sectionName.substr( 8 );
			if( std::regex_match( packageName, validPackageNamePattern ) == false ) {
				throw std::runtime_error( "invalid package name in lockfile: " + packageName );
			}
			std::unordered_map<std::string, ManifestParser::ConfigValue>& packageFields = sectionPair.second;

			LockfileEntry entry;
			entry.packageName = packageName;

			if( packageFields.count( "version" ) > 0 ) {
				entry.resolvedVersionString = packageFields["version"].stringValue;
			}
			if( packageFields.count( "integrity" ) > 0 ) {
				entry.sourceIntegrityHash = packageFields["integrity"].stringValue;
			}
			if( packageFields.count( "source" ) > 0 ) {
				entry.sourceRepository = packageFields["source"].stringValue;
			}
			if( packageFields.count( "dependencies" ) > 0 &&
				packageFields["dependencies"].valueKind == ManifestParser::ConfigValue::Kind::Array ) {
				entry.transitiveDependencyNames = packageFields["dependencies"].arrayValues;
			}

			lockfile.lockedEntries.push_back( entry );
		}

		return lockfile;
	}

	void LockfileManager::writeToFile( const Lockfile& lockfile, const std::string& filePath ) {
		std::ofstream fileStream( filePath );
		if( fileStream.is_open() == false ) {
			throw std::runtime_error( "could not write lockfile: " + filePath );
		}

		fileStream << "# This file is auto-generated by uranite-pkg. Do not edit manually.\n\n";
		fileStream << "lock:\n";
		fileStream << "  version: \"" << escapeYamlString( lockfile.lockfileFormatVersion ) << "\"\n\n";

		for( const LockfileEntry& entry : lockfile.lockedEntries ) {
			fileStream << "package:\n";
			fileStream << "  " << entry.packageName << ":\n";
			fileStream << "    version: \"" << escapeYamlString( entry.resolvedVersionString ) << "\"\n";

			if( entry.sourceIntegrityHash.empty() == false ) {
				fileStream << "    integrity: \"" << escapeYamlString( entry.sourceIntegrityHash ) << "\"\n";
			}

			if( entry.sourceRepository.empty() == false ) {
				fileStream << "    source: \"" << escapeYamlString( entry.sourceRepository ) << "\"\n";
			}

			if( entry.transitiveDependencyNames.empty() == false ) {
				fileStream << "    dependencies:\n";
				for( size_t depIndex = 0; depIndex < entry.transitiveDependencyNames.size(); depIndex++ ) {
					fileStream << "      - \"" << escapeYamlString( entry.transitiveDependencyNames[depIndex] ) << "\"\n";
				}
			}

			fileStream << "\n";
		}
	}

} // namespace uranite::pkg
